version: '3.8'

networks:
  local-network:
    name: local-network
    external: false

services:
  service-nginx:
    container_name: service-nginx
    image: nginx:latest
    build: ./docker/nginx/
    networks:
      - local-network
    depends_on:
      - service-php
    volumes:
      - ../:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/sites/:/etc/nginx/sites-enabled
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
  service-php:
    container_name: service-php
    networks: 
      - local-network
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 9000:80